// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/incrementor.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNumberResponse struct {
	Number               int32    `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNumberResponse) Reset()         { *m = GetNumberResponse{} }
func (m *GetNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetNumberResponse) ProtoMessage()    {}
func (*GetNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{0}
}

func (m *GetNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNumberResponse.Unmarshal(m, b)
}
func (m *GetNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNumberResponse.Merge(m, src)
}
func (m *GetNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetNumberResponse.Size(m)
}
func (m *GetNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNumberResponse proto.InternalMessageInfo

func (m *GetNumberResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SetSettingsRequest struct {
	IncrementSize        int32    `protobuf:"varint,1,opt,name=IncrementSize,proto3" json:"IncrementSize,omitempty"`
	MaxValue             int32    `protobuf:"varint,2,opt,name=MaxValue,proto3" json:"MaxValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSettingsRequest) Reset()         { *m = SetSettingsRequest{} }
func (m *SetSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*SetSettingsRequest) ProtoMessage()    {}
func (*SetSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{1}
}

func (m *SetSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSettingsRequest.Unmarshal(m, b)
}
func (m *SetSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSettingsRequest.Marshal(b, m, deterministic)
}
func (m *SetSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSettingsRequest.Merge(m, src)
}
func (m *SetSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_SetSettingsRequest.Size(m)
}
func (m *SetSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSettingsRequest proto.InternalMessageInfo

func (m *SetSettingsRequest) GetIncrementSize() int32 {
	if m != nil {
		return m.IncrementSize
	}
	return 0
}

func (m *SetSettingsRequest) GetMaxValue() int32 {
	if m != nil {
		return m.MaxValue
	}
	return 0
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	GUID                 string   `protobuf:"bytes,1,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{5}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_de87ca99f0450898, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetNumberResponse)(nil), "proto.GetNumberResponse")
	proto.RegisterType((*SetSettingsRequest)(nil), "proto.SetSettingsRequest")
	proto.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("internal/proto/incrementor.proto", fileDescriptor_de87ca99f0450898) }

var fileDescriptor_de87ca99f0450898 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x5f, 0x4f, 0xea, 0x40,
	0x10, 0xc5, 0x81, 0x50, 0x2e, 0x0c, 0xf7, 0x86, 0x7b, 0xe7, 0x1a, 0xc4, 0xfa, 0x42, 0x36, 0xc4,
	0x98, 0x98, 0x94, 0xa8, 0xcf, 0xc6, 0xf8, 0x87, 0x90, 0x3e, 0x68, 0x4c, 0x2b, 0xbc, 0x17, 0x1c,
	0x6b, 0x23, 0xed, 0x62, 0x77, 0xeb, 0xbf, 0x4f, 0xe9, 0x47, 0x32, 0xed, 0x6e, 0x0b, 0x48, 0xd4,
	0x07, 0x9f, 0xda, 0x73, 0x76, 0xe6, 0xcc, 0xce, 0xfe, 0xa0, 0x1b, 0x44, 0x92, 0xe2, 0xc8, 0x9b,
	0xf5, 0xe7, 0x31, 0x97, 0xbc, 0x1f, 0x44, 0xd3, 0x98, 0x42, 0x8a, 0x24, 0x8f, 0xad, 0xcc, 0x41,
	0x23, 0xfb, 0x98, 0xdb, 0x3e, 0xe7, 0xfe, 0x8c, 0x54, 0xd9, 0x24, 0xb9, 0xed, 0x53, 0x38, 0x97,
	0x2f, 0xaa, 0x86, 0xed, 0xc1, 0xbf, 0x21, 0xc9, 0xcb, 0x24, 0x9c, 0x50, 0xec, 0x90, 0x98, 0xf3,
	0x48, 0x10, 0xb6, 0xa1, 0xa6, 0x9c, 0x4e, 0xb9, 0x5b, 0xde, 0x35, 0x1c, 0xad, 0xd8, 0x18, 0xd0,
	0x25, 0xe9, 0x92, 0x94, 0x41, 0xe4, 0x0b, 0x87, 0x1e, 0x12, 0x12, 0x12, 0x7b, 0xf0, 0xc7, 0xce,
	0x67, 0xbb, 0xc1, 0x2b, 0xe9, 0xa6, 0x55, 0x13, 0x4d, 0xa8, 0x5f, 0x78, 0xcf, 0x63, 0x6f, 0x96,
	0x50, 0xa7, 0x92, 0x15, 0x14, 0x9a, 0x0d, 0xa0, 0x79, 0x92, 0xc8, 0xbb, 0x3c, 0xd0, 0x84, 0xfa,
	0x48, 0xa4, 0xab, 0x85, 0x2a, 0xab, 0xe1, 0x14, 0x3a, 0x3d, 0xbb, 0xf2, 0x84, 0x78, 0xe2, 0xf1,
	0x4d, 0x16, 0xd3, 0x70, 0x0a, 0xcd, 0x7a, 0xf0, 0x5b, 0xc5, 0xe8, 0x35, 0x36, 0xc0, 0xb8, 0xe6,
	0xf7, 0x14, 0xe9, 0x10, 0x25, 0x98, 0x0d, 0x2d, 0x87, 0xfc, 0x40, 0xc8, 0x74, 0xe1, 0x9f, 0x0d,
	0xdc, 0x81, 0xbf, 0x8b, 0x28, 0x3d, 0x14, 0xa1, 0x3a, 0x1c, 0xd9, 0xe7, 0x3a, 0x27, 0xfb, 0x67,
	0xbf, 0xc0, 0x18, 0xa4, 0x6f, 0x7e, 0xf0, 0x56, 0x01, 0xb4, 0x17, 0x9c, 0x5c, 0x8a, 0x1f, 0x83,
	0x29, 0xe1, 0x31, 0x34, 0x0a, 0x08, 0xd8, 0xb6, 0x14, 0x2f, 0x2b, 0xe7, 0x65, 0x65, 0xbd, 0x66,
	0x47, 0x19, 0xd6, 0x1a, 0x2e, 0x56, 0xc2, 0x33, 0x68, 0x15, 0xb1, 0xdf, 0xc4, 0x7c, 0xe2, 0xb3,
	0x12, 0x9e, 0x42, 0x73, 0x89, 0x2e, 0x6e, 0xe9, 0x79, 0xeb, 0xc4, 0xbf, 0xc8, 0xd8, 0x87, 0x6a,
	0x8a, 0x00, 0x51, 0x37, 0x2f, 0x61, 0x35, 0xff, 0xaf, 0x78, 0xc5, 0xdd, 0x8f, 0xa0, 0x9e, 0x3f,
	0x22, 0xb6, 0x75, 0xc9, 0x07, 0x40, 0xe6, 0xe6, 0x9a, 0x9f, 0xb7, 0x4f, 0x6a, 0xd9, 0xc9, 0xe1,
	0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x41, 0xe2, 0x60, 0x0f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IncrementorServiceClient is the client API for IncrementorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IncrementorServiceClient interface {
	GetNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetNumberResponse, error)
	IncrementNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	SetSettings(ctx context.Context, in *SetSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type incrementorServiceClient struct {
	cc *grpc.ClientConn
}

func NewIncrementorServiceClient(cc *grpc.ClientConn) IncrementorServiceClient {
	return &incrementorServiceClient{cc}
}

func (c *incrementorServiceClient) GetNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetNumberResponse, error) {
	out := new(GetNumberResponse)
	err := c.cc.Invoke(ctx, "/proto.IncrementorService/GetNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementorServiceClient) IncrementNumber(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.IncrementorService/IncrementNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementorServiceClient) SetSettings(ctx context.Context, in *SetSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.IncrementorService/SetSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementorServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.IncrementorService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementorServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.IncrementorService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementorServiceServer is the server API for IncrementorService service.
type IncrementorServiceServer interface {
	GetNumber(context.Context, *empty.Empty) (*GetNumberResponse, error)
	IncrementNumber(context.Context, *empty.Empty) (*empty.Empty, error)
	SetSettings(context.Context, *SetSettingsRequest) (*empty.Empty, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

func RegisterIncrementorServiceServer(s *grpc.Server, srv IncrementorServiceServer) {
	s.RegisterService(&_IncrementorService_serviceDesc, srv)
}

func _IncrementorService_GetNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementorServiceServer).GetNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IncrementorService/GetNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementorServiceServer).GetNumber(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementorService_IncrementNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementorServiceServer).IncrementNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IncrementorService/IncrementNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementorServiceServer).IncrementNumber(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementorService_SetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementorServiceServer).SetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IncrementorService/SetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementorServiceServer).SetSettings(ctx, req.(*SetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementorService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementorServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IncrementorService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementorServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncrementorService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementorServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IncrementorService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementorServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IncrementorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IncrementorService",
	HandlerType: (*IncrementorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumber",
			Handler:    _IncrementorService_GetNumber_Handler,
		},
		{
			MethodName: "IncrementNumber",
			Handler:    _IncrementorService_IncrementNumber_Handler,
		},
		{
			MethodName: "SetSettings",
			Handler:    _IncrementorService_SetSettings_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _IncrementorService_Auth_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _IncrementorService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/incrementor.proto",
}
