#!/usr/bin/env bash

MIGRATIONS=${MIGRATIONS:-./migrations}
MIGRATE=${MIGRATE:-migrate}

INC_SQL_DRIVER=${INC_SQL_DRIVER:-postgres}
INC_SQL_USERNAME=${INC_SQL_USERNAME:-incrementor}
INC_SQL_PASSWORD=${INC_SQL_PASSWORD:-incrementor}
INC_SQL_HOSTNAME=${INC_SQL_HOSTNAME:-127.0.0.1}
INC_SQL_PORT=${INC_SQL_PORT:-5432}
INC_SQL_DATABASE=${INC_SQL_DATABASE:-incrementor}
INC_SQL_SLLMODE=${INC_SQL_SLLMODE:-disable}

DSN=$(printf '%s://%s:%s@%s:%s/%s?sslmode=%s' "$INC_SQL_DRIVER" "$INC_SQL_USERNAME" "$INC_SQL_PASSWORD" "$INC_SQL_HOSTNAME" "$INC_SQL_PORT" "$INC_SQL_DATABASE" "$INC_SQL_SLLMODE" )

$MIGRATE -path $MIGRATIONS -database $DSN $@