#!/usr/bin/env bash

ARG1=$1

export INC_DEBUG=false

export INC_SQL_DRIVER=${INC_SQL_DRIVER:-postgres}
export INC_SQL_USERNAME=${INC_SQL_USERNAME:-incrementor}
export INC_SQL_PASSWORD=${INC_SQL_PASSWORD:-incrementor}
export INC_SQL_HOSTNAME=${INC_SQL_HOSTNAME:-127.0.0.1}
export INC_SQL_PORT=${INC_SQL_PORT:-5432}
export INC_SQL_DATABASE=${INC_SQL_DATABASE:-incrementor}
export INC_SQL_SLLMODE=${INC_SQL_SLLMODE:-disable}

export INC_LOG_LEVEL=${INC_LOG_LEVEL:-debug}
export INC_LOG_TARGET=${INC_LOG_TARGET:-syslog}
export INC_LOG_SYSLOG_ADDRESS=${INC_LOG_SYSLOG_ADDRESS:-127.0.0.1:512}
export INC_LOG_SYSLOG_NETWORK=${INC_LOG_SYSLOG_NETWORK:-udp}

export INC_SERVER_LISTEN_NETWORK=${INC_SERVER_LISTEN_NETWORK:-tcp}
export INC_SERVER_LISTEN_ADDRESS=${INC_SERVER_LISTEN_ADDRESS:-127.0.0.1:9876}
export INC_SERVER_TLS_CERTFILE=config/tls/127.0.0.1.crt
export INC_SERVER_TLS_KEYFILE=config/tls/127.0.0.1.key

export INC_CLIENT_AUTH_USERNAME=${INC_CLIENT_AUTH_USERNAME:-client-1}
export INC_CLIENT_AUTH_PASSWORD=${INC_CLIENT_AUTH_PASSWORD:-secret-password}
export INC_CLIENT_DIAL_ADDRESS=${INC_CLIENT_DIAL_ADDRESS:-127.0.0.1:9876}
export INC_CLIENT_TLS_CERTFILE=config/tls/127.0.0.1.crt

export INC_INCREMENTOR_MINVALUE=${INC_INCREMENTOR_MINVALUE:-0}
export INC_INCREMENTOR_MAXVALUE=${INC_INCREMENTOR_MAXVALUE:-21474836471222}
export INC_INCREMENTOR_INCREMENTBY=${INC_INCREMENTOR_INCREMENTBY:-1}

export INC_JWT_SECRET=${INC_JWT_SECRET:-my_secret_key}
export INC_JWT_DURATION=${INC_JWT_DURATION:-1d}

REALPATH=`realpath $0`
DIRPATH=`dirname $REALPATH`

if [[ "$ARG1" == "build" ]]; then
    INCREMENTOR="go run $DIRPATH/../cmd/incrementor"
else
    INCREMENTOR=$DIRPATH/../bin/incrementor
fi

$INCREMENTOR server
