#!/usr/bin/env bash

ARG1=$1

INC_SQL_DRIVER=${INC_SQL_DRIVER:-postgres}
INC_SQL_USERNAME=${INC_SQL_USERNAME:-incrementor}
INC_SQL_PASSWORD=${INC_SQL_PASSWORD:-incrementor}
INC_SQL_HOSTNAME=${INC_SQL_HOSTNAME:-127.0.0.1}
INC_SQL_PORT=${INC_SQL_PORT:-5432}
INC_SQL_DATABASE=${INC_SQL_DATABASE:-incrementor}
INC_SQL_SLLMODE=${INC_SQL_SLLMODE:-disable}

INC_LOG_LEVEL=${INC_LOG_LEVEL:-debug}
INC_LOG_TARGET=${INC_LOG_TARGET:-syslog}
INC_LOG_SYSLOG_ADDRESS=${INC_LOG_SYSLOG_ADDRESS:-127.0.0.1:512}
INC_LOG_SYSLOG_NETWORK=${INC_LOG_SYSLOG_ADDRESS:-127.0.0.1:512}

INC_SERVER_LISTEN_NETWORK=${INC_SERVER_LISTEN_NETWORK:-tcp}
INC_SERVER_LISTEN_ADDRESS=${INC_SERVER_LISTEN_ADDRESS:-127.0.0.1:9876}
INC_SERVER_TLS_CERTRILE=config/tls/127.0.0.1.crt
INC_SERVER_TLS_KEYFILE=config/tls/127.0.0.1.key

INC_CLIENT_AUTH_USERNAME=${INC_CLIENT_AUTH_USERNAME:-client-1}
INC_CLIENT_AUTH_PASSWORD=${INC_CLIENT_AUTH_PASSWORD:-secret-password}
INC_CLIENT_DIAL_ADDRESS=${INC_CLIENT_DIAL_ADDRESS:-127.0.0.1:9876}
INC_CLIENT_TLS_CERTFILE=config/tls/127.0.0.1.crt

INC_INCREMENTOR_MINVALUE=${INC_INCREMENTOR_MINVALUE:-0}
INC_INCREMENTOR_MAXVALUE=${INC_INCREMENTOR_MAXVALUE:-2147483647}
INC_INCREMENTOR_INCREMENTBY=${INC_INCREMENTOR_INCREMENTBY:-1}

INC_JWT_SECRET=${INC_JWT_SECRET:-my_secret_key}
INC_JWT_DURATION=${INC_JWT_DURATION:-1d}

REALPATH=`realpath $0`
DIRPATH=`dirname $REALPATH`

if [[ "$ARG1" == "build" ]]; then
    INCREMENTOR="go run $DIRPATH/../cmd/incrementor"
else
    INCREMENTOR=$DIRPATH/../bin/incrementor
fi

$INCREMENTOR server